### ISSUE TITLE
Cocoapods?

### ISSUE THREAD

**Issue by Spacelapp** [BLPoonia/BLMultiColorLoader#1]

**Comment by pooniawalla** [comment]
@Spacelapp Actually right now I don't know how to create a cocoapod. I'm learning that. Can you help me out with that?

**Comment by Spacelapp** [comment]
https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by rico237** [comment]
Would you like me to make it for you ? @BLPoonia

**Comment by pooniawalla** [comment]
@rico237 yeah, sure! Please go ahead!

**Comment by pooniawalla** [comment]
@rico237 : Merged your pull request, there seems to be some issue with the pod.
It says "Pod Invalid".
Can you check?

**Comment by rico237** [comment]
yeah i just needed you to merge the files first to submit pod

**Comment by rico237** [comment]
@BLPoonia or set a tag with version 0.1.0 for the main repository

**Comment by rico237** [comment]
then i can push the pod

**Comment by rico237** [comment]
@BLPoonia  Could you give me write access to git ?

https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by rico237** [comment]
Closing issue, BLMultiLoader is on cocoapod :)

**Comment by pooniawalla** [comment]
@rico237 Thanks for the contribution... We can close this now.
